### PR TITLE
CI: Adjust pagefile size on Windows to avoid unnecessary noise

### PR DESCRIPTION
**Pull request by skalarproduktraum**
This PR adjusts the pagefile size on the Github Actions Windows runners, to avoid random out-of-memory errors for memory-intensive unit tests.

### CODE REVIEW

**Comment by elect86** [comment]
What kind of noise are you referring to?

**Review by elect86 — APPROVED** [review]
Fine for me

**Comment by skalarproduktraum** [comment]
Some builds on Windows were randomly running out of memory, especially when running protein tests, which are quite memory-consuming, but optimised to a reasonable extent now. I've now searched **_THE INTERNET_** if people experience similar issues, and yes, they did. Problem is solved by increasing the pagefile size, which this PR does 👍 

I'm also limiting info logging more and have optimised the output options for the Gradle test runner, so exceptions are much easier to spot in the logs 🚀

**Comment by skalarproduktraum** [comment]
Thanks for the review, @elect86 👍

**Comment by elect86** [comment]
This was the issue with the "Window 17" platform?

**Pull request merged**
