### PR TITLE
BioJava NullpointerException

### PR DESCRIPTION
**Pull request by Domino2357**
Added a catch for NullPointerException and updated BioJava. The latter seems to solve the issue, though we can't be certain since the error was occurring nondeterministically.
I was thinking about changing the error message to: "NullPointerException in the BioJava-Code occurred. Please update BioJava and see if this resolves the issue. If not, please contact burger@mpi-cbg.de" What do you think @skalarproduktraum ?

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
Sorry, but I fundamentally disagree this is a good strategy :-/ You can't just say "oh yeah something went wrong, please update the biojava version" without having a clue _what actually went wrong_. Please try to run the tests until you've found what actually went wrong. Even if it is on the biojava side, we still need to know what's the issue -- even if it's just caused by a connection problem or something.

**Comment by Domino2357** [comment]
Admittedly, that's a good point. I'll check.

**Comment by Domino2357** [comment]
Okay, after digging deeper we know the following:
The NullPointerException occurs deterministically -- the indeterminism stems from us testing randomly 20 out of 80 entries. In the BioJava-Code the issue was a missing Null-safeguard against a residue-type being not defined (in MmtfStructureReader.java, line 217). This has been resolved in the latest stable version (5.4.0). Consequently, our dependency has been updated. The reason why this happened just recently and never before is a recent change in the rcsb database (https://www.rcsb.org/structure/6SLM, also screenshot).
image

**Bottom-Line** the issue was an update to the database leading to a NullPointerException in BioJava and is resolved in the (new) version 5.4.0.

**Comment by Domino2357** [comment]
@skalarproduktraum I think this is good to go.

**Comment by skalarproduktraum** [comment]
Thanks @Domino2357 for figuring this out!

**Pull request merged**
