### PR TITLE
Curve Geometry

### PR DESCRIPTION
**Pull request by Domino2357**
This pull request contains the catmull rom spline and a the geometry riding along the curve as well as an example and some unit test.

### CODE REVIEW

**Comment by Domino2357** [comment]
Heyho!
I have no idea why this doesn't work with the other pull request but this new pull request contains everything we want without the redundant commits. Would it be a problem to discard the old pull request and use this one instead, @skalarproduktraum ?

**Comment by skalarproduktraum** [comment]
No problem to close the old one and use this one, we just need to see why the CI is now failing ;)

**Comment by skalarproduktraum** [comment]
So there still seems to be an issue with your unit tests, please verify. The failures on both Travis and Appveyor are genuine failures. Please also try to run the tests locally via `mvn test`.

**Comment by Domino2357** [comment]
@skalarproduktraum Finally! :)

**Comment by skalarproduktraum** [comment]
Great! Four (hopefully :-D) final things:

* why is the `drawSpline` method there? Couldn't that stuff already be done in the constructor? Feels like a bit of an ugly API, sorry
* please rename `CurveGeometry` to `Curve`
* in CatmullRomSplineTests, the test is a little bit weak, just testing that the curve creation doesn't fail. Could you come up with something more exhaustive there please?
* pom.xml got an extra new line that should not be there

**Comment by Domino2357** [comment]
@skalarproduktraum I hope this is it. If you still have improvements I could do, please let me know!

**Comment by skalarproduktraum** [comment]
Looks good to me, thank you!

**Pull request merged**
