### PR TITLE
New packagin

### PR DESCRIPTION
**Pull request by Domino2357**
This should do the job and solve the issue with @frauzufall branch. I merged the master into this one, thus, the merging into master should go smooth. Also, I did not change things besides moving things into different packages and deleting one minor test class I wrote.

### CODE REVIEW

**Comment by Domino2357** [comment]
@frauzufall does the rebase on this work?
Otherwise, this should be ready to merge -- the build in Linux fails because of #390 which is taken care of by #392.

**Comment by frauzufall** [comment]
@Domino2357 something's still off and I can't rebase. If you look into the commit list here, 9 days ago all commits were added a second time somehow. The last commit in the history on my branch from `newPackagin` is `753651d8` - which is exactly the commit prior to the point where all commits appear a second time. Can we reset to this commit and merge master again? Happy to do that with you / talk it through!

**Comment by Domino2357** [comment]
@frauzufall I reverted and fixed some import-issues. Would you mind checking if you can rebase? If so, this should be ready to go.

**Comment by Domino2357** [comment]
Heyho @frauzufall, the rebase is not possible automatically, however, from the first glance it seems we are only dealing with some renaming issues. If that's correct, this should be easy to resolve. Happy to talk to you if that seems helpful to you.

**Comment by skalarproduktraum** [comment]
Closed because superceeded by #411.

**Pull request closed without merging**
