### PR TITLE
Cam controls add-ons

### PR DESCRIPTION
**Pull request by xulman**
A few tiny changes towards better and nicer scenery (and SciView) :-)

### CODE REVIEW

**Comment by xulman** [comment]
That commit introduces explicit "mouse move sensitivity" attribute into FPS -- it is implemented entirely ala Arcball

**Comment by xulman** [comment]
(hmm, was expecting commits listing and messages to be interleaved)

The arcball-commits:
- code tidy
- fix when scrolling/zooming-in-out: initial `distance` was set a node was selected, it could have been moved since then but the `distance` got no update, then zooming-in-out was not doing the expected job (because it had no accurate `distance` info)

**Comment by xulman** [comment]
(also the order of commits is changed, interesting...: the MovementCOmmand-commit should not be between the two for arcball...)

the `MovementCommand` is code cosmetics and a bit of optimization: rather then computing `cross()` freshly, we leverage on the camera's `right()` vector (which is always updated with every camera change and so here the `cross()` is not computed 2nd-time)

**Comment by skalarproduktraum** [comment]
So this PR actually introduces something I did deliberately prevent: rotation around the axis of sight. What's the reasoning behind introducing this? If truly necessary, I'd propose creating an additional CameraControl on top of ArcballCameraControl to include this.

**Comment by xulman** [comment]
ok, please then ignore the last commit (https://github.com/scenerygraphics/scenery/pull/323/commits/6cf9fb5a6ccf6c6bc6f0ec8e9bfdb6682cd9581e) in this PR and consider only the rest.. so that we could close it potentially

**Comment by xulman** [comment]
sooo:
- I've reverted (via the force push that replaced only the last commit 6cf9fb5) any change to the original ArcBall and FPS cam controls -- they should stay intact in this PR functionality-wise,
- I would love to have added the new class (class name is welcomed subject to change) that does ArcBall with the sticky-y-axis (formely branded as flexi-y-axis)
- aaah, actually, I propose to rename `node` to `camNode` in ArcBall and updated doc (in a hope that difference between the two arcballs would be clear(er)

I couldn't see easy way to implant the *use of* the new class into scenery, we would have to change
https://github.com/scenerygraphics/scenery/blob/cefd4470ef7f1fdc055c55ad82cdce07f9933083/src/main/kotlin/graphics/scenery/SceneryBase.kt#L376
most likely and this one has state variable, and... 

I wanted to have the stickyYArcball as a *regime* of the original, so either you work with FPS or with ArcBall (and you could separately define which particular ArcBall should be used)... so it shall not be FPS->ArcBall->StickyYArcBall->FPS but rather FPS->oneOfArcBall->FPS

As a result, the new class in not used anywhere in scenery.... (sorry for that). But, I use it in sciview:
https://github.com/scenerygraphics/sciview/compare/master...xulman:addingStickyYArcball
where you can ctrl-shift-A-Y  (even a cat would have a hard time to turn it on by accident) replace what is used for Arcballing

Would that be good?

-----------------
I was wondering about a boolean switch in the original Acrball.kt... I think it would have made everything much simpler, less error-prone in sciview code (there would have been always on object for arcball, not two like I am proposing above, no need to update always both to have them synced), but such flag is most likely not clean code type of thing (on the other hand, one can think of it as of another param to the code, similarily to, e.g., mouseSpeed param -- we also don't have separate arcball object for every speed rate)

I am saying if possibly the https://github.com/scenerygraphics/sciview/pull/273 becomes a reality, we would need to extend the https://github.com/scenerygraphics/sciview/pull/273/commits/871d12e7604a6354aecd9bf0ae7c5a6f645556c9 - a governing class that updates/forwards controls param changes to the relevant controllers, and most likely more I don't even *remember now*... (that is the motor for me to be writing this paragraphs)

**Comment by xulman** [comment]
deprecated in favour of #329

**Pull request closed without merging**
