### PR TITLE
Volume measurement

### PR DESCRIPTION
**Pull request by Domino2357**
Native support for volume measuring (of meshes!) for scenery.

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
I think this looks reasonable, let's discuss on Friday though in detail. And until then, please have a look at the issues Codacy is complaining about 👍

**Comment by Domino2357** [comment]
@skalarproduktraum this should be fine.

**Comment by skalarproduktraum** [comment]
@Domino2357 is this ready to go?

**Comment by Domino2357** [comment]
Yes, please!

**Pull request merged**
