### PR TITLE
Fix BoundingBox Bug for Proteins

### LINKED ISSUE #413: Bounding boxes are not generated correctly for RibbonDiagrams
### Steps to reproduce
Call `getMaximumBoundingBox()` on a `RibbonDiagram` instance, e.g. created via `val diagram = RibbonDiagram(Protein.fromID("2zzw"))`.

### Expected result
The function should return a non-empty bounding box.

### Actual result
An empty bounding box, with min and max containing the null vector, is returned.

### PR DESCRIPTION
**Pull request by Domino2357**
This fixes #413. The problem was that the positions were not well defined for subCurves in the Curve class.

### CODE REVIEW

**Comment by Domino2357** [comment]
@skalarproduktraum this should be fine.

**Comment by Domino2357** [comment]
The failing tests do not seem to occur because of the one line in Curve changed.

**Comment by skalarproduktraum** [comment]
@Domino2357 The CameraTests issue is again something OpenCL-related. However, the rendering errors for proteins in the Argos checks are not: https://www.argos-ci.com/scenerygraphics/scenery/builds/290 Could you please have a look and see what's the problem there? Thanks!

**Comment by skalarproduktraum** [comment]
Any news here, @Domino2357?

**Comment by Domino2357** [comment]
Thanks for checking in @skalarproduktraum ! I don't know how to assign the right positions for the subcurves. All vertices are stored correctly, but I never specified a position. Naively, its just the centroid of all vertices but this breaks the rendering. Also, the first splinePoint, i.e., the beginning of each subcurve deosn't work either. Is there a way to specify the position when all vertex positions are already in place?

**Comment by skalarproduktraum** [comment]
Not sure I understand the question, @Domino2357 😵 What do you mean by "Is there a way to specify the position when all vertex positions are already in place?" -- do you want to modify the vertex buffer without rewriting everything?

**Comment by Domino2357** [comment]
@skalarproduktraum sorry that was put clumsy. My problem is once I defined a position for each subcurve, the rendering breaks. I tried to use the centroid of the vertices as the position as well as the starting point of the sub-spline. My question is: how can one define a position without changing the vertices positions?

**Comment by skalarproduktraum** [comment]
@Domino2357 This PR would need a merge of master 👍

**Pull request merged**
