### PR TITLE
Add support for protein sidechain visualisation

### PR DESCRIPTION
**Pull request by Domino2357**
Allows for choosing sidechains manually and makes them visible on click in VR.

Merged with #428, which makes #428 obsolete.

### CODE REVIEW

**Comment by Domino2357** [comment]
@skalarproduktraum to me, it looks like the gitlab test fails because of some internal error and not because of the pull request.

**Comment by skalarproduktraum** [comment]
@Domino2357 If you merge the latest master here, this should build again nicely, and could be merged then 👍

**Comment by Domino2357** [comment]
@skalarproduktraum I merged master into the branch. Argos returns an error, however, the screenshots look fine to me. What do you think?

**Comment by skalarproduktraum** [comment]
@Domino2357 Is this still current, could I merge it?

**Comment by skalarproduktraum** [comment]
Poke @Domino2357

**Comment by Domino2357** [comment]
@skalarproduktraum Yes! Please, I am sorry for not answering. Checked it again, it looks fine.

**Comment by skalarproduktraum** [comment]
Would you be so kind to merge the latest master into your PR here, and push again, so we see current CI results? Also, please correct the typo in `VRSidecChainsExample` 👍

**Pull request merged**
