### PR TITLE
Vk enhanced

### PR DESCRIPTION
**Pull request by elect86**
first sketch

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
TODO:

- [ ] make the CI builds work
- [ ] change to meaningful commit messages
- [ ] use vkk as dependency rather than inline

**Comment by elect86** [comment]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-rules) on project scenery: Execution enforce-rules of goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce failed. NullPointerException -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException Command exited with code 1`

It looks like is not on my side...

**Comment by skalarproduktraum** [comment]
Hey @elect86,

you're getting this message from the enforcer, because it does not allow snapshot dependencies. Please see if it builds right locally with e.g. `mvn clean package -Denforcer.skip=true`. This whole procedure is just there to ensure that commits that end up in master build reprocibly, which is not ensured with SNAPSHOT versions. 3.2.1 will be out in the next days so I guess the issue will resolve itself 👍

**Comment by elect86** [comment]
enforcer still fails

**Pull request closed without merging**
