### PR TITLE
Ribbon rainbow

### PR DESCRIPTION
**Pull request by Domino2357**
The ribbons should also be displayable with a rainbow colour map

### CODE REVIEW

**Comment by Domino2357** [comment]
Oh, maybe I should create a package for the protein stuff? Seems a bit inconvenient to have all these classes swimming in the main package, what do you think, @skalarproduktraum?

**Comment by skalarproduktraum** [comment]
Yes, @Domino2357, putting them in a separate package seems reasonable. I think @elect86 has already looked into reorganising a bit, maybe we can continue this discussion here? I think stuff like Curve, CatmullRomSpline, etc could go into a package `geometry`, while the geometric primitives like Box, etc could go into `primitives`. Mesh things could go into `mesh`. Opinions? Maybe also from @kephale ?

**Comment by elect86** [comment]
Mesh things are few (1, 2?), so I'd do as follows: a `graphics.scenery.mesh` root package with `geometry` and `primitives` underneath (which are logical subsets)

**Comment by Domino2357** [comment]
@elect86 I like the idea! When @skalarproduktraum gives his approval, I'll do it

**Comment by skalarproduktraum** [comment]
I think this is getting a bit too deep/segmented, how about putting the Mesh stuff in `geometry` as well, and have `primitives` on the same level?

**Comment by skalarproduktraum** [comment]
I'd also be fine with having `geometry.primitives`

**Comment by Domino2357** [comment]
Agreed! Maybe burying the primitives too deep is not an optimal idea.
I'd prefer to do another pull request for the packaging if that is alright

**Comment by skalarproduktraum** [comment]
Yes, that sounds good. I'd merge that PR now then, and then you can do the magic sorting hat 👍

**Pull request merged**
