### PR TITLE
Volume: Improved raycast behaviour

### PR DESCRIPTION
**Pull request by skalarproduktraum**
This PR fixes the volume ray caster to only sample from volumes within their own bounding box.

### CODE REVIEW

**Comment by skalarproduktraum** [comment]
Did you also add the `localNear` and `localFar` keys in the place where you've created the VolumeManager? This is also not (yet) done in the CustomVolumeManagerExample.

**Comment by skalarproduktraum** [comment]
Is this good to merge, @aryaman-gupta?

**Comment by skalarproduktraum** [comment]
Ping again @aryaman-gupta

**Comment by aryaman-gupta** [comment]
@skalarproduktraum sorry for the delay in replying

Unfortunately, when a volume is sliced into multiple chunks, some artefacts are visible at the borders. It appears as though a single slice of voxels is not sampled correctly. The attached image is an example. The image shows the Stagbeetle dataset (Meister Eduard Gröller, Georg Glaeser, Johannes Kastner, 2005)

DistributedVolumeRenderer - 2022-05-25 00 02 31

To reproduce, the easiest way may be to run the `VolumeFromFileExample` of the `scenery-insitu` repository. Before running the application, the Stagbeetle dataset would need to be divided into two parts and placed in directories named Part1 and Part2, each with its own `stacks.info` file indicating the dimensions of the respective part.

**Comment by skalarproduktraum** [comment]
Superseded by #622.

**Pull request closed without merging**
